# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HMFGraph_Gem_algorithm_cpp <- function(iters, S, B, p, n, stop_criterion, delta, nu, inter, epsilon1, epsilon2, fixed_B, print_t, omega_0, phi_0 = NULL) {
    .Call(`_HMFGraph_HMFGraph_Gem_algorithm_cpp`, iters, S, B, p, n, stop_criterion, delta, nu, inter, epsilon1, epsilon2, fixed_B, print_t, omega_0, phi_0)
}

Hierarchical_wishart_Gem_algorithm_cpp <- function(iters, S, B, p, n, stop_criterion, delta, nu, inter, epsilon1, epsilon2, fixed_B, print_t, omega_0) {
    .Call(`_HMFGraph_Hierarchical_wishart_Gem_algorithm_cpp`, iters, S, B, p, n, stop_criterion, delta, nu, inter, epsilon1, epsilon2, fixed_B, print_t, omega_0)
}

Matrix_F_Gem_algorithm_cpp <- function(iters, S, B, p, n, stop_criterion, delta, nu, inter, print_t, omega_0) {
    .Call(`_HMFGraph_Matrix_F_Gem_algorithm_cpp`, iters, S, B, p, n, stop_criterion, delta, nu, inter, print_t, omega_0)
}

gibbs_algorithm_cpp <- function(iters, S, B, p, n, delta, nu, epsilon1, epsilon2, fixed_B = FALSE, print_t = TRUE, a_lim = 0.0001, b_lim = 10000, Omega0) {
    .Call(`_HMFGraph_gibbs_algorithm_cpp`, iters, S, B, p, n, delta, nu, epsilon1, epsilon2, fixed_B, print_t, a_lim, b_lim, Omega0)
}

hwo_Gem_algorithm_cpp <- function(iters, S, B, p, n, stop_criterion, delta, nu, inter, epsilon1, epsilon2, fixed_B, print_t, omega_0, gamma1, gamma2) {
    .Call(`_HMFGraph_hwo_Gem_algorithm_cpp`, iters, S, B, p, n, stop_criterion, delta, nu, inter, epsilon1, epsilon2, fixed_B, print_t, omega_0, gamma1, gamma2)
}

interval_adjacency <- function(lower, upper, k) {
    .Call(`_HMFGraph_interval_adjacency`, lower, upper, k)
}

mvrnorm_cpp <- function(n, mu, Sigma) {
    .Call(`_HMFGraph_mvrnorm_cpp`, n, mu, Sigma)
}

rajat_Cpp <- function(mat1, mat2, k, lvt) {
    .Call(`_HMFGraph_rajat_Cpp`, mat1, mat2, k, lvt)
}

rcpparma_hello_world <- function() {
    .Call(`_HMFGraph_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_HMFGraph_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_HMFGraph_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_HMFGraph_rcpparma_bothproducts`, x)
}

shuffle_matrix <- function(data, seed_number) {
    .Call(`_HMFGraph_shuffle_matrix`, data, seed_number)
}

